### PR TITLE
Add Russian translation

### PR DESCRIPTION
**Pull request by bocharsky-bw**

### CODE REVIEW

**Review by jrushlow — APPROVED** [review]
Thanks @bocharsky-bw for adding these translations!

**Comment by weaverryan** [comment]
Thanks again Victor! Next up Spanish translations???

**Comment by bocharsky-bw** [comment]
Haha, I hoped for @larzuk91  :p

**Comment by larzuk91** [comment]
Yeah! I can do the Spanish translates if nobody has done it already

**Comment by jrushlow** [comment]
that would be awesome!

**Pull request merged**
